### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by timhuff2000**
Hay man, check it out.

### CODE REVIEW

**Comment by timhuff2000** [comment]
More comments...looks good
https://github.com/timhuff2000

**Comment by timhuff2000** [comment]
Merge me please

**Comment by timhuff2000** [comment]
Another comment

**Comment by watkins101** [comment]
Looks good TFA. I say merge that dude right there.

**Comment by timhuff2000** [comment]
Looks good

**Comment by timhuff2000** [comment]
Looks good

**Pull request merged**
